### ISSUE TITLE
make sure dates are correct

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/blog_threefold#4]
e.g 
![image](https://user-images.githubusercontent.com/64129/82331179-101ab380-99e4-11ea-86a8-74a64d1fc316.png)

otherwise these will be pushed to the very end as "invalid posts" and won't be sorted.
https://github.com/threefoldfoundation/blog_threefold/search?q=published_at&unscoped_q=published_at

**Comment by VonSub** [comment]
done
